// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService exposes system-level utility APIs.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates triggers an immediate update check.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateCheckResult> {
    return $Call.ByID(2851822347).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetUpdateCheckOptions returns current update checker options.
 */
export function GetUpdateCheckOptions(): $CancellablePromise<$models.UpdateCheckOptions> {
    return $Call.ByID(3048177455).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetVersion returns app version.
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(2865931044);
}

/**
 * HandleURLScheme handles URL Scheme invocations.
 */
export function HandleURLScheme(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1311417232, rawURL);
}

/**
 * Ping responds with pong.
 */
export function Ping(): $CancellablePromise<string> {
    return $Call.ByID(399080868);
}

/**
 * ResolvemcpvmcpPath resolves the mcpvmcp executable path.
 */
export function ResolvemcpvmcpPath(): $CancellablePromise<string> {
    return $Call.ByID(4220615561);
}

/**
 * SetUpdateCheckOptions updates update checker options.
 */
export function SetUpdateCheckOptions(opts: $models.UpdateCheckOptions): $CancellablePromise<$models.UpdateCheckOptions> {
    return $Call.ByID(128000755, opts).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdateCheckResult.createFrom;
const $$createType1 = $models.UpdateCheckOptions.createFrom;
