// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsService from "./wailsservice.js";
export {
    WailsService
};

export {
    ConfigModeResponse,
    CoreStateResponse,
    InfoResponse,
    Manager,
    ObservabilityConfigDetail,
    ProfileDetail,
    ProfileSummary,
    PromptEntry,
    PromptPage,
    RPCConfigDetail,
    RPCTLSConfigDetail,
    ResourceEntry,
    ResourcePage,
    RuntimeConfigDetail,
    ServerSpecDetail,
    ToolEntry
} from "./models.js";
