// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsService from "./wailsservice.js";
export {
    WailsService
};

export {
    ActiveCaller,
    ConfigModeResponse,
    CoreStateResponse,
    CreateProfileRequest,
    DeleteProfileRequest,
    DeleteServerRequest,
    ImportMcpServersRequest,
    ImportServerSpec,
    InfoResponse,
    InstanceStatus,
    Manager,
    ObservabilityConfigDetail,
    PoolStats,
    ProfileDetail,
    ProfileSummary,
    PromptEntry,
    PromptPage,
    RPCConfigDetail,
    RPCTLSConfigDetail,
    ResourceEntry,
    ResourcePage,
    RuntimeConfigDetail,
    ServerInitStatus,
    ServerRuntimeStatus,
    ServerSpecDetail,
    ToolEntry,
    UpdateCallerMappingRequest,
    UpdateServerStateRequest
} from "./models.js";
